from django.db import models

class PersonalAd(models.Model):
    id2 = models.CharField(max_length=255)
    subcl = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    datetime = models.CharField(max_length=255)
    ImageLink = models.CharField(max_length=255)
    ImageTitle = models.CharField(max_length=255)
    postText = models.TextField()
    postTitle = models.CharField(max_length=255)
    postID = models.IntegerField(primary_key=True)
    postClass = models.CharField(max_length=255)
    lat = models.CharField(max_length=255)
    long = models.CharField(max_length=255)
    link = models.CharField(max_length=255)
    ih = models.CharField(max_length=255)
    itempp = models.CharField(max_length=255)
    itempn = models.CharField(max_length=255)
    itempx = models.CharField(max_length=255)
    itemcg = models.CharField(max_length=255)
    i = models.CharField(max_length=255)
    itempnr = models.CharField(max_length=255)
    dataPid = models.CharField(max_length=255)
    pl = models.CharField(max_length=255)
    title1 = models.CharField(max_length=255)
    title2 = models.CharField(max_length=255)
    l2 = models.CharField(max_length=255)
    timezone = models.CharField(max_length=255)
    datetime2 = models.CharField(max_length=255)
    postCategory = models.CharField(max_length=255)
    age = models.CharField(max_length=255)
    location = models.CharField(max_length=255)

    def __unicode__(self):
        return u'%s\n%s' % (self.postID, self.postTitle)
